config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'pages#profile', as: 'profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :matches
  resources :chats, only: [:index]

  get '/faker', to: 'faker#index'

  resources :movies, only: [:index, :show] do
    resources :liked_movies, only: [:create, :destroy]
    # post 'toggle_favorite', on: :member
  end

  resources :chats, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="autoModal" tabindex="-1" aria-labelledby="autoModalLabel" aria-hidden="true" data-controller="auto-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 style="font-size: 21px;" class="modal-title" id="autoModalLabel">Find your buddy</h5>
        <%= link_to users_path do %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <% end %>
      </div>
      <div class="modal-body">
        <h3 style="font-size: 16px; text-align: center; line-height: 2;">See who liked the same movies as you<br>and<br>Match with your buddy!</h3>
      </div>
      <div class="modal-footer">
        <%= link_to users_path do %>
        <button type="button" class="btn modal-btn" data-bs-dismiss="modal">Let's go!</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# <div class="modal fade" id="autoModal2" tabindex="-1" aria-labelledby="autoModalLabel2" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 style="font-size: 21px;" class="modal-title" id="autoModalLabel2">Find your buddy</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3 style="font-size: 16px; text-align: center; line-height: 2;"> Like someone?&nbsp; Tap &nbsp; &nbsp;<i class="fa-solid fa-heart"></i><br>Mutual likes lead to matches!</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-target="#autoModal" data-bs-toggle="modal" data-bs-dismiss="modal">Back</button>
        <%= link_to users_path do %>
        <%# <button type="button" class="btn modal-btn" data-bs-dismiss="modal">Let's go!</button>
        <% end %>
      <%# </div>
    </div>
  </div>
</div> %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="container-fluid">
<ul class="navbar-nav me-auto flex-row">
<% if user_signed_in? %>
<li class="nav-item active">
<%= link_to profile_path(current_user), class: "nav-link" do %>
<% if current_user.photo.attached? %>
<%= cl_image_tag current_user.photo.key, crop: :fill, class: 'profile-img-icon' %>
<% else %>
<%= image_tag("default-avatar.png", size: "30x30", class: 'profile-img-icon') %>
<% end %>
<% end %>
            </li>
            <li class="nav-item">
              <%= link_to movies_path, class: "nav-link" do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
            <li class="nav-item">
    <%= link_to chats_path, class: "nav-link" do %>
      <i class="fa-regular fa-message"></i>
    <% end %>
 </li>
 <li class="nav-item">
  <%= link_to users_path, class: "nav-link" do %>
  <i class="fa-solid fa-users"></i>
  <% end %>
 </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
                <i class="fa-solid fa-right-from-bracket"></i>
              <% end %>
            </li>
          <% else %>
             <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
           <% end %>
           </ul>
    </div>
  </div>
</div>

<%# <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "My Profile", profile_path, class: "nav-link" %>
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "My Chats", chats_path, class: "nav-link" %>
          <%# </li> %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          <%# </li> %>
        <%# <% else %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%# </li> %>
        <%# <% end %>
      <%# </ul> %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>
<%#  %>