config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'pages#profile', as: 'profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :matches
  resources :chats, only: [:index]

  get '/faker', to: 'faker#index'

  resources :movies, only: [:index, :show] do
    resources :liked_movies, only: [:create, :destroy]
    # post 'toggle_favorite', on: :member
  end

  resources :chats, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :match
  # user and match user
  has_many :messages, dependent: :destroy
  # validate that the same user and match only have one chat
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    # @chats = Chat.all
    @match_ids = current_user.get_all_matches.pluck(:id)
    @chats = Chat.where(match_id: @match_ids)
    # If I'm logged in I should only see my matches (current_user.matches)
    # get all my matches and all the ID of the matches
  # @chats = current_user.matches.includes(:chat).map(&:chat).compact

  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
      # add part of the messages
  end

  # create method to create chat between me and the match user
end

app/views/chats/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <h1 style="margin-top: 30px;">Inbox</h1>
  <div class="avatar-list">
    <% @chats.each do |chat| %>
      <% other_user = chat.match.user == current_user ? chat.match.user_match : chat.match.user %>
      <%= link_to chat_path(chat), class: "avatar-link" do %>
        <% if other_user.photo.attached? %>
          <%= cl_image_tag other_user.photo.key, class: "avatar-img" %>
        <% else %>
          <% random_avatar_url = "https://picsum.photos/50?random=#{other_user.id}" %>
          <%= image_tag random_avatar_url, class: "avatar-img" %>
        <% end %>
      <% end %>
    <% end %>
  </div>

<div class="container card-container">
  <% @chats.each do |chat| %>
    <% other_user = chat.match.user == current_user ? chat.match.user_match : chat.match.user %>
    <%= link_to chat_path(chat), class: "user-card-link" do %>
      <div class="card-product my-2">
        <div class="card-product-img">
          <% if other_user.photo.attached? %>
            <%= cl_image_tag other_user.photo.key %>
          <% else %>
            <% random_avatar_url = "https://picsum.photos/50?random=#{other_user.id}" %>
            <%= image_tag random_avatar_url %>
          <% end %>
        </div>
    <% end %>
        <div class="d-flex align-items-center">
          <div class="card-product-infos">
            <h2><%= other_user.name %></h2>
            <% last_message = chat.messages.order(created_at: :desc).first %>
            <% if last_message %>
              <p><%= truncate(last_message.content, length: 50) %></p>
              <p class="chat-time"><%= last_message.created_at.strftime("%H:%M") %></p>
            <% else %>
              <p>Start the conversation!</p>
              <p class="chat-time">---</p>
            <% end %>
          </div>
        </div>
      </div>
  <div class="container chat-costum-line"></div>
  <% end %>
</div>



<%# if the chat.match.user = current_user display the name of user.match
if the other way around I want to display the user  %>

app/views/chats/show.html.erb
<div class="container">
  <div class="row">
  <%= link_to chats_path, class: "user-card-link", style: "color: #FFFFFF;" do %>
    <i class="fa-solid fa-arrow-left-long" style="position: absolute; top: 40px; left: 20px;"></i>
  <% end %>
  </div>
  <div class="container chatroom" data-controller="chat-subscription"
      data-chat-subscription-chatroom-id-value="<%= @chat.id %>"
      data-chat-subscription-current-user-id-value="<%= current_user.id %>">

    <div class="messages" data-chat-subscription-target="messages">
      <% @chat.messages.each do |message| %>
        <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' :
        'justify-content-start' %>">
          <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for [@chat, @message],
    html: {
      class: "d-flex",
      data: {
        action: "turbo:submit-end->chat-subscription#resetForm"
        }
      } do |f|
    %>
    <div class="input">
      <%= f.input :content,
        class: "chat-form",
        label: false,
        # placeholder: "Message ##{@chat.name}",
        wrapper_html: {class: "flex-grow-1"}
      %>
      <%= button_tag(type: 'submit', class: 'btn btn-sent') do %>
      <i class="fa-solid fa-paper-plane"></i>
      <% end %>
    <% end %>
    </div>
  </div>
  <%# <%= link_to "Back to Chats", chats_path, class: 'confirm-button' %>
</div>