config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'pages#profile', as: 'profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :matches
  resources :chats, only: [:index]

  get '/faker', to: 'faker#index'

  resources :movies, only: [:index, :show] do
    resources :liked_movies, only: [:create, :destroy]
    # post 'toggle_favorite', on: :member
  end

  resources :chats, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/views/pages/ profile.html.erb
<div class="container">
  <div class="profile-card">
    <%= link_to users_path, class: "user-card-link" do %>
      <i class="fa-solid fa-left-long" style="position: absolute; top: 10px; left: 15px;"></i>
    <% end %>
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: 'profile-img' %>
    <% else %>
      <%= image_tag("default-avatar1.png", class: 'profile-img') %>
    <% end %>
    <div class="user-container" style="position: absolute; bottom: 50px">
      <h1><%= @user.name %></h1>
      <div class="d-flex align-items-center">
        <p><%= @user.age %></p>
        <i class="fa-solid fa-heart fa-2xl" style="color: #BEBFC1; position: absolute; left: 320px;"></i>
      </div>
    </div>
  </div>
  <div class="container mt-4">
    <p><%= @user.description %></p>
  </div>
  <div class="container">
    <h2>Liked Movies</h2>
    <div class="cards row col-12 mt-4">
      

app/views/pages/home.html.erb
<span class="home">
<%= stylesheet_link_tag 'application', media: 'all' %>
<div class="intro">
  <h1>Welcome to Cinema Buddy</h1>
  <h3>Swipe, chat & share the big screen</h3>
  <% if current_user %>
    <%= link_to 'Start now', movies_path, class: 'btn-grad' %>
  <% else %>
    <%= link_to 'Register', new_user_session_path, class: 'btn-grad' %>
  <% end %>
</div>
</span>

app/views/pages/profile.html.erb
<%# <div class="page-container-profile"> %>
  <%# <h1 class="my-profile-heading">My Profile</h1> %>

  <%# <div class="profile-card user-details"> %>
    <%# <% if @user.photo.attached? %>
      <%# <%= cl_image_tag @user.photo.key, class: 'profile-img' %>
    <%# <% else %>
      <%# <%= image_tag("default-avatar.png", class: 'profile-img') %>
    <%# <% end %>
    <%# <div class="user-container" style="position: absolute; bottom: 50px"> %>
      <%# <h2><%= @user.name</h2> %>
      <%# <div class="d-flex align-items-center"> %>
        <%# <p><%= @user.age</p> %>

      <%# </div> %>
      <%# <div class="field"> %>
        <%# <%= f.label :age, class: "large-label"<br> %>
        <%# <%= f.number_field :age, class: "large-input" %>
      <%# </div> %>
      <%# <div class="field"> %>
        <%# <%= f.label :description, class: "large-label"<br> %>
        <%# <%= f.text_area :description, class: "large-textarea" %>
      <%# </div> %>
    <%# <% end %>
  <%# </div> %>

  <%# <h2 class="liked-movies">Liked Movies:</h2> %>
  <%# <% @user.liked_movies.each do |liked_movie| %>
    <%# <div class="card-category"> %>
      <%# <div class="card-image" style="background-image: url(<%= liked_movie.movie.photo_url);"></div> %>
      <%# <%= liked_movie.movie.title %>
    <%# </div> %>
  <%# <% end %>
  <%# </div> %>

  <%# <div class="d-flex justify-content-end mt-3"> %>
    <%# <%= link_to 'Edit My Profile', edit_registration_path(@user), class: "edit-profile-btn" %>
  <%# </div> %>

  <div class="container">
  <h1 class="my-profile-heading">My Profile</h1>
  <div class="profile-card">
    <%= link_to movies_path, class: "user-card-link" do %>
      <i class="fa-solid fa-left-long" style="position: absolute; top: 10px; left: 15px;"></i>
    <% end %>
    </div>
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: 'profile-img' %>
    <% else %>
      <%= image_tag("default-avatar1.png", class: 'profile-img') %>
    <% end %>
    <div class="user-container" style="position: absolute; bottom: 50px">
      <h2><%= @user.name %></h2>
      <div class="d-flex align-items-center">
        <p><%= @user.age %></p>
      </div>
    </div>
  </div>
  <div class="container mt-4">
    <p><%= @user.description %></p>
  </div>
  <div class="container">
    <h2>Liked Movies</h2>
    <div class="cards row col-12 mt-4">
    </div>
  </div>
</div>
<%= link_to 'Edit My Profile', edit_user_path(@user), class: "btn btn-primary" %>