config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'profile', to: 'pages#profile', as: 'profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
  resources :users
  resources :matches
  resources :chats, only: [:index]

  get '/faker', to: 'faker#index'

  resources :movies, only: [:index, :show] do
    resources :liked_movies, only: [:create, :destroy]
    # post 'toggle_favorite', on: :member
  end

  resources :chats, only: [:index, :show] do
    resources :messages, only: :create
  end
end

app/controllers/faker_controller.rb
class FakerController < ApplicationController

  # def index
  #   liked_movies_ids = current_user.liked_movies.pluck(:movie_id)
  #   @users = User.includes(:liked_movies).where(liked_movies: { movie_id: liked_movies_ids }) # checking they have the same movies
  #   users = users.where.not(user: current_user) #current_user not included
  #   check that they are not a current match users = users + filter of having a match - match instance with pending = false. for current_user
  #   @users = @users.distinct

  #   @users = User.all
  #   if params[:query].present?
  #     @users = @users.where("name ILIKE ?", "%#{params[:query]}%")
  #   end
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: @users }
  #   end
  # end

  def index
    liked_movies_ids = current_user.liked_movies.pluck(:movie_id)
    users = User.includes(:liked_movies).where(liked_movies: { movie_id: liked_movies_ids }) # checking they have the same movies
    users = users.where.not(id: current_user.id) #current_user not included
    users = users.where.not(id: Match.where(user_id: current_user.id).or(Match.where(user_match_id: current_user.id, pending: false)))# check that they are not a current match users = users + filter of having a match - match instance with pending = false for current_user
    @users = users.distinct

    # @users = User.all
    if params[:query].present?
      @users = @users.where("name ILIKE ?", "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end
end

app/views/faker/index.html.erb
<div class="row">
  <%= link_to movies_path, class: "user-card-link", style: "color: #ffffff;" do %>
    <i class="fa-solid fa-arrow-left-long" style="position: absolute; top: 20px; left: 20px;"></i>
  <% end %>
</div>
<div class="container card-container">
  <%= render 'shared/modal' %>
  <%= form_tag users_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query, params[:query], class: "form-control search-form", placeholder: "Search profiles" %>
    <button type="submit" class="btn" style="position: absolute; right: 40px; top: 140px;">
      <i class="fa-solid fa-magnifying-glass" style="color: rgba(255, 255, 255, 0.3);"></i>
    </button>
  <% end %>
  <% @users.each do |user| %>
    <%= link_to user_path(user), class: "user-index-card-link" do %>
      <div class="card-product-index-users my-3">
        <div class="card-product-img">
          <% if user.photo.attached? %>
            <%= cl_image_tag user.photo.key %>
          <% else %>
            <% random_avatar_url = "https://picsum.photos/500/500?random=#{user.id}" %>
            <%= image_tag random_avatar_url %>
          <% end %>
        </div>
    <% end %>
        <div class="d-flex align-items-center">
          <div class="card-product-infos-index-users">
            <h2 id="user-list"><strong><%= user.name %></strong>, <%= user.age %></h2>
            <p class="descriptions-limit"><%= user.description %><br>
              <%= link_to user_path(user), class: "user-index-card-link", style: "color: #ffa2cb;" do %>
              see more...
              <% end %>
            </p>
          </div>
          <%= render 'matches/heart', user: user %>
        </div>
    </div>
  <% end %>
</div>

<%# And then add the usual text-decoration: none;  etc to your flat-card-link  CSS %>